behaviors:
  AutoParking:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.00035
      beta: 0.004
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.3
        demo_path: Demos/AutoParkingDemo_0.demo
        use_actions: false
        use_vail: false

    behavioral_cloning: 
      demo_path: Demos/AutoParkingDemo_0.demo
      steps: 750000
      strength: 0.2

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 40000000
    summary_freq: 100000
    threaded: true
        
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
torch_settings:
  device: cuda
